### ISSUE TITLE
Plain js and seamless-immutable? 

### ISSUE THREAD

**Issue by wmertens** [mattbierner/js-hashtrie-benchmark#6]
Hi, 

Would 
you be interested in a PR adding benchmarks for plain JS objects and seamless-immutable? They are not hashtries but I think they provide interesting data points for comparison. 

See https://github.com/rtfeldman/seamless-immutable/issues/7#issuecomment-78381615

**Comment by mattbierner** [comment]
Thanks for the suggestion. However both of these are too slow for the benchmarks. We are testing maps sizes between 10 and 100,000 for many tests, and updating an immutable JS object is an `O(N)` operation whereas all of these tree based libraries are `O(log(N))`.

Also, at the small sizes (10) JS objects should blow away all of these implementations. I would be concerned with the performance you are currently seeing.

Let me know if you feel this is incorrect. I would happily add benchmarks for a non-hashtrie based immutable map, but it does need to meet some baseline performance requirements.
